<?xml version="1.0" encoding="UTF-8"?>
<Spec_File>
   <FileHeader>
      <Element>
         <Name><![CDATA[Caret-Version]]></Name>
         <Value><![CDATA[5.64]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[Date]]></Name>
         <Value><![CDATA[2012-05-20T20:35:56]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[category]]></Name>
         <Value><![CDATA[Individual]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[encoding]]></Name>
         <Value><![CDATA[XML]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[space]]></Name>
         <Value><![CDATA[OTHER]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[species]]></Name>
         <Value><![CDATA[Human]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[structure]]></Name>
         <Value><![CDATA[right]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[subject]]></Name>
         <Value><![CDATA[cerebral]]></Value>
      </Element>
   </FileHeader>
   <CLOSEDtopo_file>
      <file1><![CDATA[Conte69.R.164k_fs_LR.topo.gii]]></file1>
   </CLOSEDtopo_file>
   <CUTtopo_file>
      <file1><![CDATA[colin.cerebral.R.flat.164k_fs_LR.topo.gii]]></file1>
   </CUTtopo_file>
   <FIDUCIALcoord_file>
      <file1><![CDATA[Conte69.R.midthickness.164k_fs_LR.coord.gii]]></file1>
   </FIDUCIALcoord_file>
   <INFLATEDcoord_file>
      <file1><![CDATA[Conte69.R.inflated.164k_fs_LR.coord.gii]]></file1>
   </INFLATEDcoord_file>
   <VERY_INFLATEDcoord_file>
      <file1><![CDATA[Conte69.R.very_inflated.164k_fs_LR.coord.gii]]></file1>
   </VERY_INFLATEDcoord_file>
   <FLATcoord_file>
      <file1><![CDATA[colin.cerebral.R.flat.164k_fs_LR.coord.gii]]></file1>
   </FLATcoord_file>
   <scene_file>
      <file1><![CDATA[atlas.R.standard-scenes-v2.164k_fs_LR.scene]]></file1>
   </scene_file>
   <paint_file>
      <file1><![CDATA[RSN-networks.R.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[parcellations_VGD11b.R.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <border_color_file>
      <file1><![CDATA[parcellations_VGD11b.bordercolor]]></file1>
   </border_color_file>
   <borderproj_file>
      <file1><![CDATA[Brodmann.164k_fs_LR.borderproj]]></file1>
   </borderproj_file>
   <borderproj_file>
      <file1><![CDATA[parcellations_VGD11b.R.164k_fs_LR.borderproj]]></file1>
   </borderproj_file>
   <metric_file>
      <file1><![CDATA[Conte69.R.MyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[Conte69.R.SmoothedMyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <surface_shape_file>
      <file1><![CDATA[Conte69.R.164k_fs_LR.shape.gii]]></file1>
   </surface_shape_file>
   <foci_file>
      <file1><![CDATA[RSN-nodes_PCN11.R.c5.foci]]></file1>
   </foci_file>
   <foci_color_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[RSN-nodes_PCN11.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[Parcels_class.focicolor]]></file1>
   </foci_color_file>
   <fociproj_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.R.164k_fs_LR.c5.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[RSN-nodes_PCN11.R.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[Parcels_GV11.R.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <study_metadata_file>
      <file1><![CDATA[Power_Neuron11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[VanEssen_CC12.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Yeo_JNP11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Glasser_JN11.study]]></file1>
   </study_metadata_file>
</Spec_File>
